### ISSUE TITLE
compile error on gtx 750

### ISSUE THREAD

**Issue by hamnaz** [alek76-2/vs-kangaroo-hybrid#2]
device = gtx 460
command : make gpu=1 ccap=20 all
make setting
CXX        = g++
CUDA       = /usr/local/cuda-8.0
CXXCUDA    = /usr/bin/g++-4.8
NVCC       = $(CUDA)/bin/nvcc

![image](https://user-images.githubusercontent.com/42878992/78471345-0e55a300-774a-11ea-92f4-44cada235bb4.png)

**Comment by alek76-2** [comment]
GPU resources, unfortunately, also have their limitations. Maximum number of 32-bit registers per thread. It is 63 for cc 2.x and 3.0, 128 for cc 1.x and 255 for cc 3.5
