### ISSUE TITLE
Cpu + GPU

### ISSUE THREAD

**Issue by kpot87** [alek76-2/vs-kangaroo-hybrid#6]
Hi! How to run CPU and GPU if I choose -t 16 my CPU is 0mh/s , GPU working fine

**Comment by alek76-2** [comment]
In main.cpp
Comment out // if (useGpu) nbCPUThread = 0;

**Comment by kpot87** [comment]
Tnx

**Comment by kpot87** [comment]
and also i received this message 

[error] Check Output Data GPU and Compute keys, thId: 00011189

what to do?

**Comment by austinm101** [comment]
ive ran into this issue too it says this http://prntscr.com/rx8823

**Comment by kpot87** [comment]
[-][ 00:06:16 ;  69.6M j/s; [GPU 66.57 Mj/s]  32.0Gj 98947761.9%; dp/kgr=139484.5; 00:00:00 ]
[error] Check Output Data GPU and Compute keys, thId: 3872291143
 Check  key: 18E00000001
    Point x: 624CD0E3B0806C2F0DDE0DA97AC247E4749E56BF680C38F3A11FD02C0178380D
 DP Point x: 18E18FBBDF3
[\][ 00:06:18 ;  69.0M j/s; [GPU 66.00 Mj/s]  32.0Gj 99315618.5%; dp/kgr=140200.5; 00:00:00 ]
1 Compared lines Tame 3670 = Wild 4712
Tame Distance: 0x0000000000000000000000000000000000000000000000000000018700000002
Wild Distance: 0x0000000000000000000000000000000000000000000000000000018200000002
2 Compared lines Tame 3670 = Wild 4854
Tame Distance: 0x0000000000000000000000000000000000000000000000000000018700000002
Wild Distance: 0x0000000000000000000000000000000000000000000000000000018600000002
3 Compared lines Tame 3670 = Wild 4872
Tame Distance: 0x0000000000000000000000000000000000000000000000000000018700000002
Wild Distance: 0x0000000000000000000000000000000000000000000000000000018600000002
SOLVED: 0x100000000
Tame Distance: 0x18700000002
Wild Distance: 0x18600000002
Tips: 1NULY7DhzuNvSDtPkFzNo6oRTZQWBqXNE9  ;-)

[i] Comparator time: 103.456 msec wild.txt 644389 bytes tame.txt 511293 bytes
[i] Success saved to file testpriv.txt
[i] No Cleaning wild.txt and tame.txt

[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[prvkey#30] 0x0000000000000000000000000000000000000000000000000000000000000000
[pubkey-check] failed!
[i]  85.9M j/s;  32.0Gj of  32.0Kj 99344106.9%; DP 5T+7W=116725+163760=280485; dp/kgr=140242.5;
[runtime]  00:06:19
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[DATE(utc)] 13 Apr 2020 09:51:20
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[x] EXIT

what does it mean where the problem?

**Comment by kpot87** [comment]
Thank you! And last question, do you know the way to know the range where private Key located (if I know publicly). It’s not for puzzles. Thank you

**Comment by alek76-2** [comment]
> 
> 
> Thank you! And last question, do you know the way to know the range where private Key located (if I know publicly). It’s not for puzzles. And it’s possible to use multiple pubkey from file to check them all ? And also it’s possible to check not one bit(2^30 for example) - range(2^30:2^50) ? And when the script(program) running there you can find % of done work and this % rise until error where DB table overflow (it can be million %). Question when it’s possible to close program and start another range, I mean after 100% it’s necessary to wait until table overflow, it can be found something from 100% to n% or it just waisted a time? And can you help with parram -p how it define of type of the card( for example RTX 2080/ 2080TI? Thanks

**Comment by alek76-2** [comment]
Your questions are strange. It is impossible to find out the range, since the public key algorithm uses a kind of asymmetric encryption! You also won’t be able to find out the% of work done, since you don’t know the maximum value of the private key. The -p parameter specifies the length of the jumps, the step of saving selected points, and does not determine the type of map. Read the 2 previous topics on the forum and you will no longer have questions!
